django_database_form/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from debug_toolbar.toolbar import debug_toolbar_urls


urlpatterns = [
    path('admin/', admin.site.urls),
    path('store/', include('store.urls', namespace="store")),
    path('order/', include('order.urls', namespace="order"))
]


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += debug_toolbar_urls()

order/urls.py
from django.urls import path
from . import views

app_name = "order"
urlpatterns = [
    path("cart/", views.cart, name="cart"),
    path("checkout/", views.checkout, name="checkout"),
]

store/urls.py
from django.urls import path
from . import views

app_name="store"
urlpatterns = [
    path("", views.index, name="index"),
    path("category/", views.category_listings, name="category_listings"),
    path("category/<slug:slug>/", views.category_listings, name="category_listings"),
    path("product/<slug:slug>/", views.product, name="product"),
    path("contact/", views.contact, name="contact")
]

templates/reusable_components/modal-search.html
<form action="." method="GET">
<div class="modal fade" id="searchModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-fullscreen">
        <div class="modal-content rounded-0">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Search by keyword</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body d-flex align-items-center">
                <div class="input-group w-75 mx-auto d-flex">
                    <input name="q" type="search" class="form-control p-3" placeholder="keywords"
                           aria-describedby="search-icon-1">
                    <button type="submit" id="search-icon-1" class="input-group-text p-3"><i class="fa fa-search"></i></button>
                </div>
            </div>
        </div>
    </div>
</div>
</form>

templates/reusable_components/nav.html
{% block nav %}
<div class="container-fluid fixed-top">
    <div class="container topbar bg-primary d-none d-lg-block">
        <div class="d-flex justify-content-between">
            <div class="top-info ps-2">
                <small class="me-3"><i class="fas fa-map-marker-alt me-2 text-secondary"></i> <a href="#"
                                                                                                 class="text-white">123
                    Street, New York</a></small>
                <small class="me-3"><i class="fas fa-envelope me-2 text-secondary"></i><a href="#" class="text-white">Email@Example.com</a></small>
            </div>
            <div class="top-link pe-2">
                <a href="#" class="text-white"><small class="text-white mx-2">Privacy Policy</small>/</a>
                <a href="#" class="text-white"><small class="text-white mx-2">Terms of Use</small>/</a>
                <a href="#" class="text-white"><small class="text-white ms-2">Sales and Refunds</small></a>
            </div>
        </div>
    </div>
    <div class="container px-0">
        <nav class="navbar navbar-light bg-white navbar-expand-xl">
            <a href="{% url 'store:index' %}" class="navbar-brand"><h1 class="text-primary display-6">Fruitables</h1></a>
            <button class="navbar-toggler py-2 px-3" type="button" data-bs-toggle="collapse"
                    data-bs-target="#navbarCollapse">
                <span class="fa fa-bars text-primary"></span>
            </button>
            <div class="collapse navbar-collapse bg-white" id="navbarCollapse">
                <div class="navbar-nav mx-auto">
                    <a href="{% url 'store:index' %}" class="nav-item nav-link {{ home }}">მთავარი</a>
                    <a href="{% url 'store:category_listings' %}" class="nav-item nav-link {{ shop }}">მაღაზია</a>
{#                    <a href="{% url 'store:product' 'raspberry' %}" class="nav-item nav-link {{ detail }}">Shop Detail</a>#}
                    <div class="nav-item dropdown">
                        <a href="#" class="nav-link dropdown-toggle" data-bs-toggle="dropdown">კატეგორიები</a>
                        <div class="dropdown-menu m-0 bg-secondary rounded-0">
                            <a href="{% url 'store:category_listings' 'xili' %}" class="dropdown-item">ხილი</a>
                            <a href="{% url 'store:category_listings' 'bostneuli' %}" class="dropdown-item">ბოსტნეული</a>
                        </div>
                    </div>
                    <a href="{% url 'store:contact' %}" class="nav-item nav-link {{ contact }}">კონტაქტი</a>
                </div>
                <div class="d-flex m-3 me-0">
                    <button class="btn-search btn border border-secondary btn-md-square rounded-circle bg-white me-4"
                            data-bs-toggle="modal" data-bs-target="#searchModal"><i
                            class="fas fa-search text-primary"></i></button>
                    <a href="{% url 'order:cart' %}" class="position-relative me-4 my-auto">
                        <i class="fa fa-shopping-bag fa-2x"></i>
                        <span class="position-absolute bg-secondary rounded-circle d-flex align-items-center justify-content-center text-dark px-1"
                              style="top: -5px; left: 15px; height: 20px; min-width: 20px;">{{ cart_count }}</span>
                    </a>
                    <a href="#" class="my-auto">
                        <i class="fas fa-user fa-2x"></i>
                    </a>
                </div>
            </div>
        </nav>
    </div>
</div>
{% endblock nav %}

templates/reusable_components/spinner.html
<div id="spinner"
     class="show w-100 vh-100 bg-white position-fixed translate-middle top-50 start-50  d-flex align-items-center justify-content-center">
    <div class="spinner-grow text-primary" role="status"></div>
</div>